### ISSUE TITLE
vehdata.name problem

### ISSUE THREAD

**Issue by itsAlphaMF** [Project-Sloth/qb-dispatch#8]
Hello,

I am using qb-dispatch with qb-vehiclekeys and qb-lock. I am getting an error on client/cl_extraalerts.lua line 182. I am assuming it is not able to draw the vehicle info properly to export. Can you tell me what other options I can try here? Gunshot, gunshots from vehicle, drug sale, officer down, speeding all work properly...I just cant get this properly. Thank you for your help
<img width="880" alt="error" src="https://user-images.githubusercontent.com/102562997/160744132-b5d12ca9-9330-4635-883e-1164087572e2.png">
!

**Comment by pushkart2** [comment]
Are you passing the vehicle from where you trigger the alert?

**Comment by pushkart2** [comment]
https://github.com/Project-Sloth/qb-dispatch/commit/2ee0c96bc5ae0c0c4f5d56fc8b4596679c02ff75

Fixed it in this commit, just pass the vehicle with the alert.

**Comment by itsAlphaMF** [comment]
Thank you for your help. This got the alert to trigger. However, it displays all information except the vehicle plate and name. I think I still have an issue with model = and plate =. Any ideas what else I could try here? No errors in console either.
